squash: false
build_from:
  arm64: georgegebbett/recipe-buddy:v2.0.6
  aarch64: georgegebbett/recipe-buddy:v2.0.6
  amd64: georgegebbett/recipe-buddy:v2.0.6
  armv7: georgegebbett/recipe-buddy:v2.0.6
  i386: georgegebbett/recipe-buddy:v2.0.6
args: {}
