---
name: Recipe Buddy for Grocy
version: dev-docker-based
slug: rbuddy-grocy
description: Recipe import system for Grocy
url: https://github.com/schblondie/recipebuddy-homeassistant
panel_icon: mdi:chef-hat
startup: system
arch:
- aarch64
- amd64
- armv7
- i386
boot: auto
init: false
map:
- config:rw
- ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
options:
  GROCY_API_KEY: YOUR_GROCY_API_KEY
  GROCY_BASE_URL: YOUR_GROCY_BASE_URL 
  NEXTAUTH_SECRET: YOUR_AUTH_SECRET
  NEXTAUTH_URL: http://localhost:3005
schema:
  GROCY_API_KEY: str
  GROCY_BASE_URL: str
  NEXTAUTH_SECRET: str
  NEXTAUTH_URL: str
ingress: true
